### ISSUE TITLE
Tests do not find PyLib, wrong search path.

### ISSUE THREAD

**Issue by rapgro** [bcdev/jpy#109]
Hi. I try to build a package for Fedora. When maven is called, it automatically executes tests but it fails to find PyLib properly due to wrong path setting. It's not possible to use setup.py --maven, because we don't want to let maven download automagically missing dependencies.
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.jpy.PyLibTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.033 sec <<< FAILURE! - in org.jpy.PyLibTest
org.jpy.PyLibTest  Time elapsed: 0.033 sec  <<< ERROR!
java.lang.ExceptionInInitializerError
        at org.jpy.PyLibTest.setUpClass(PyLibTest.java:30)
Caused by: java.lang.RuntimeException: missing configuration property 'jpy.jpyLib'
        at org.jpy.PyLibTest.setUpClass(PyLibTest.java:30)

Running org.jpy.JavaReflectionTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.jpy.JavaReflectionTest
Running org.jpy.PyLibWithSysPathTest
class org.jpy.PyLibWithSysPathTest: code source: file:/home/builder/rpmbuild/BUILD/python-jpy-0.8/python2/target/test-classes/
PyLibWithSysPathTest: starting Python with 'sys.path' extension: /home/builder/rpmbuild/BUILD/python-jpy-0.8/python2/target/test-classes/pymodules
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE! - in org.jpy.PyLibWithSysPathTest
org.jpy.PyLibWithSysPathTest  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.jpy.PyLib
        at org.jpy.PyLibWithSysPathTest.setUpClass(PyLibWithSysPathTest.java:50)

Running org.jpy.PyModuleTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in org.jpy.PyModuleTest
org.jpy.PyModuleTest  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.jpy.PyLib
        at org.jpy.PyModuleTest.setUp(PyModuleTest.java:37)

org.jpy.PyModuleTest  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.jpy.PyLib
        at org.jpy.PyModuleTest.tearDown(PyModuleTest.java:45)

Running org.jpy.PyObjectTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in org.jpy.PyObjectTest
org.jpy.PyObjectTest  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.jpy.PyLib
        at org.jpy.PyObjectTest.setUp(PyObjectTest.java:42)

org.jpy.PyObjectTest  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.jpy.PyLib$Diag
        at org.jpy.PyObjectTest.tearDown(PyObjectTest.java:50)

Running org.jpy.jsr223.Jsr223Test
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.jpy.jsr223.Jsr223Test

Results :

Tests in error: 
  PyLibTest.setUpClass:30 ExceptionInInitializer
  PyLibWithSysPathTest.setUpClass:50 NoClassDefFound Could not initialize class ...
org.jpy.PyModuleTest.org.jpy.PyModuleTest
  Run 1: PyModuleTest.setUp:37 NoClassDefFound Could not initialize class org.jpy.PyLib
  Run 2: PyModuleTest.tearDown:45 » NoClassDefFound Could not initialize class org.jpy....

org.jpy.PyObjectTest.org.jpy.PyObjectTest
  Run 1: PyObjectTest.setUp:42 NoClassDefFound Could not initialize class org.jpy.PyLib
  Run 2: PyObjectTest.tearDown:50 NoClassDefFound Could not initialize class org.jpy.Py...


Tests run: 10, Failures: 0, Errors: 4, Skipped: 0

[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Skipping Java-Python Bridge
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.161 s
[INFO] Finished at: 2017-09-24T13:21:11+02:00
[INFO] Final Memory: 17M/156M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project jpy: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/builder/rpmbuild/BUILD/python-jpy-0.8/python2/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by forman** [comment]
> It's not possible to use setup.py --maven, 

Which command have you used for building/testing?

**Comment by rapgro** [comment]
Please provide documentation about how to build, install and run tests properly.

**Comment by rapgro** [comment]
i found in build.log:
```
org.jpy.PyLibTest  Time elapsed: 0.049 sec  <<< ERROR!
java.lang.ExceptionInInitializerError
        at org.jpy.PyLibTest.setUpClass(PyLibTest.java:30)
Caused by: java.lang.RuntimeException: missing configuration property 'jpy.jpyLib'
        at org.jpy.PyLibTest.setUpClass(PyLibTest.java:30
```

**Comment by forman** [comment]
Again, could you first please provide the command you have entered to build `jpy` and which caused the error.

You're right, installation docs may be updated to also address the problem you currently have.

**Comment by rapgro** [comment]
We can not use the magic --maven switch in Fedora because we do some magic to maven as well, e.g. to run it with special resolver for locally available dependencies only.
For me, it's not clear if maven should run before or after python compilation. When can those tests run successfully?
I'll attach the build.log grepped for used commands (without any additional output, for relevant parts see above):
```
umask 022
cd /home/builder/rpmbuild/BUILD
cd /home/builder/rpmbuild/BUILD
rm -rf python-jpy-0.8
/usr/bin/mkdir -p python-jpy-0.8
cd python-jpy-0.8
/usr/bin/gzip -dc /home/builder/rpmbuild/SOURCES/jpy-0.8.tar.gz
/usr/bin/tar -xof -
STATUS=0
'[' 0 -ne 0 ']'
/usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
mv jpy-0.8 python3
find python3 -maxdepth 1 -name '*.md' -or -name '*.txt' -or -name '*.rst' -print -exec ln -s '{}' -t. ';'
pushd python3
sed -i 's:'\''mvn'\'':'\''xmvn'\'', '\''-o'\'':' setup.py jpyutil.py
popd
exit 0
umask 022
cd /home/builder/rpmbuild/BUILD
cd python-jpy-0.8
export JAVA_HOME=/usr/lib/jvm/java
JAVA_HOME=/usr/lib/jvm/java
true ----- python3
pushd python3
/usr/bin/python3 /usr/share/java-utils/mvn_build.py
```
* Do not wonder about the special python3 subfolger. It's possible to build separately for python2 as well but it's the same issue then.

**Comment by forman** [comment]
Hope to find some time next week to explain, improve `setup.py`, and update `README.md`.

**Comment by EmergentOrder** [comment]
I get the same issue when I run `python setup.py --maven bdist_wheel` followed by `mvn clean install` on Ubuntu.

**Comment by COA1IMB** [comment]
Me too, has someone found solution ?
