### ISSUE TITLE
Undefined symbol

### ISSUE THREAD

**Issue by ledebroux** [bcdev/jpy#113]
Hey,

When calling `PyLib.startPython()` (in a temporary main, with the properties set), I get the following:

    org.jpy.PyLib: entered static initializer
    org.jpy.PyLibConfig: entered static initializer
    org.jpy.PyLibConfig: exited static initializer
    org.jpy.PyLib: System.load("/home/ldebrou/files/blak/script_engine/jpy/build/lib.linux-x86_64-2.7/jpy.so")
    Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/ldebrou/files/blak/script_engine/jpy/build/lib.linux-x86_64-2.7/jpy.so: /home/ldebrou/files/blak/script_engine/jpy/build/lib.linux-x86_64-2.7/jpy.so: undefined symbol: _Py_ZeroStruct
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at org.jpy.PyLib.loadLib(PyLib.java:340)
        at org.jpy.PyLib.<clinit>(PyLib.java:389)
        at com.iba.blak.ui.controller.ScriptEngineScene.main(ScriptEngineScene.java:218)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

    Process finished with exit code 1

As far as my knowledge goes, I'm using python2.7 all the way.
Is there something obviously wrong that I might do ?

**Comment by ledebroux** [comment]
I saw it could come from pythonLib not being given.
I added a line to my config which is now: 

    -Djpy.jpyLib=/home/ldebrou/files/blak/script_engine/jpy-0.8/build/lib.linux-x86_64-2.7/jpy.so
    -Djpy.jdlLib=/home/ldebrou/files/blak/script_engine/jpy-0.8/build/lib.linux-x86_64-2.7/jdl.so
    -Djpy.pythonLib=/usr/lib/x86_64-linux-gnu/libpython2.7.so
    -Djpy.debug=true

I also saw that I misspelled jdl for jpl...

But anyway, it now seems to work.

**Comment by forman** [comment]
:)

**Comment by forman** [comment]
Can we close this?

**Comment by ledebroux** [comment]
Yes it can be closed, sorry for the non-issue :).
