### ISSUE TITLE
PyDictWrapper keys/values broken in Python 3

### ISSUE THREAD

**Issue by devinrsmith** [bcdev/jpy#160]
Calling `PyDictWrapper#keys` or `PyDictWrapper#values` in the context of Python 3 causes

```
RuntimeError: java.lang.ClassCastException: Can not convert non-list type to a list!
    at org.jpy.PyObject.asList(PyObject.java:256)
    at org.jpy.PyDictWrapper.keySet(PyDictWrapper.java:112)
```

Dictionary keys and values are views in Python 3.

https://blog.labix.org/2008/06/27/watch-out-for-listdictkeys-in-python-3

**Comment by devinrsmith** [comment]
Also, `has_key` is no longer a method in Python 3. https://portingguide.readthedocs.io/en/latest/dicts.html

**Comment by devinrsmith** [comment]
Also, `has_key` is no longer a method on dict in Python 3. https://portingguide.readthedocs.io/en/latest/dicts.html

**Comment by devinrsmith** [comment]
(Will be submitting MR soon)
