### ISSUE TITLE
help to install jpy for windows8

### ISSUE THREAD

**Issue by antonio19812** [bcdev/jpy#66]
Could anyone help me in installing jpy in windows8 ? I have problems yet at the beginning of the installation

**Comment by forman** [comment]
What's the problem? What have you tried so far?

**Comment by hczerpak** [comment]
I'm having a problem on Windows 10 with installation. My JDK_HOME and JAVA_HOME are both set to "C:\Program Files\Java\jdk1.8.0_71" where my JDK is. If I try to run 

python setup.py --maven build

I'm getting 

Using /cygdrive/d/projects/jpy/jpyutil.pyc
Error: Cannot find any JVM shared library

What do? :(

**Comment by hczerpak** [comment]
I've spend whole day today trying to successfully build this. 
My environment variables are set to 32-bit java. I've installed Pyton 2.7 and 3.5 32-bit. All sorts of Visual Studios and .NET stuff.

For short moment I was able to pass jpy.jar build and now it fails again on 

`error: Unable to find vcvarsall.bat`

One thing I don't understand is what is what exactly. In section "Build for Microsoft Windows Python 2.7" you linked 
Microsoft Visual C++ 10 or higher (link: `http://www.microsoft.com/en-us/download/details.aspx?id=8279`)

and then in section "Build for Microsoft Windows Python 3.3 and higher" you linked 
Microsoft Windows SDK 7.1 or higher (link: `http://www.microsoft.com/en-us/download/details.aspx?id=8279`)

Is it the same stuff? Link looks the same. MS Visual C++ 10, MS Windows SDK 7.1 sounds quite different but none of this helped with `error: Unable to find vcvarsall.bat` and messing around with `VS90COMNTOOLS` env var. None of that stuff had that file after installation.

After installing Microsoft Visual C++ Compiler for Python 2.7 (from here `https://www.microsoft.com/en-us/download/details.aspx?id=44266`) it passed that point but now Java tests are failing.

Why can't I just download a jar or add maven dependency? Even if I don't want to run anything on my development machine I'd like to be able to develop. I may run it somewhere else but I just want to work on stuff. Adding this dependency you mention in installation doesn't work either:

<dependency>
<groupId>org.jpy</groupId> <artifactId>jpy</artifactId> <version>0.8</version>
</dependency>

So I can't even use api. 

Will try reinstall all again and hope for the best

**Comment by hczerpak** [comment]
Using P2.7 I'm getting this 

`       at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

org.jpy.PyModuleTest  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.jpy.PyLib
        at org.jpy.PyLib$Diag.<clinit>(PyLib.java:80)
        at org.jpy.PyModuleTest.tearDown(PyModuleTest.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.jpy.PyObjectTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0 sec <<< FAILURE!
org.jpy.PyObjectTest  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.jpy.PyLib
        at org.jpy.PyObjectTest.setUp(PyObjectTest.java:42)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

org.jpy.PyObjectTest  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.jpy.PyLib$Diag
        at org.jpy.PyObjectTest.tearDown(PyObjectTest.java:50)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Tests in error:
  org.jpy.PyLibTest: D:\projects\jpy\build\lib.win32-2.7\jpy.pyd: Can't find dependent libraries
  org.jpy.PyLibWithSysPathTest: Could not initialize class org.jpy.PyLib
  org.jpy.PyModuleTest: Could not initialize class org.jpy.PyLib
  org.jpy.PyModuleTest: Could not initialize class org.jpy.PyLib
  org.jpy.PyObjectTest: Could not initialize class org.jpy.PyLib
  org.jpy.PyObjectTest: Could not initialize class org.jpy.PyLib$Diag

Tests run: 12, Failures: 0, Errors: 6, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.831 s
[INFO] Finished at: 2016-02-11T15:22:56+00:00
[INFO] Final Memory: 12M/31M`

**Comment by hczerpak** [comment]
Next time I run the same command I got different error:

`Running D:\projects\jpy\src\test\python\jpy_rt_test.py
..............
----------------------------------------------------------------------
Ran 14 tests in 0.008s

OK
Error occurred during initialization of VM
Could not reserve enough space for 524288KB object heap

Running D:\projects\jpy\src\test\python\jpy_diag_test.py
..
----------------------------------------------------------------------
Ran 2 tests in 0.001s

OK
setting environment variable 'PYTHONPATH' to None
1 Python unit test(s) failed. Installation is likely broken.`

Clearly there is a problem with memory during build process.

**Comment by hczerpak** [comment]
I've lowered jvm_maxmem value on your python tests and now I'm getting past python tests but build fails on java tests with messages mentioned above. Will keep trying.
