### ISSUE TITLE
Running python from Java raises Symbol not found: _PyBool_Type

### ISSUE THREAD

**Issue by mariobriggs** [bcdev/jpy#79]
I am on Mac OS 10.10.4 (14E46). Built jpy from sources successfully 

When i try to run python from java, get the following error

java -cp ./lib/jpy-0.9-SNAPSHOT.jar:. -Djpy.jpyLib=./build/lib.macosx-10.6-intel-3.5/jpy.cpython-35m-darwin.so -Djpy.jdlLib=./build/lib.macosx-10.6-intel-3.5/jdl.cpython-35m-darwin.so Test

Exception in thread "main" java.lang.UnsatisfiedLinkError: /XXX/jpy/build/lib.macosx-10.6-intel-3.5/jpy.cpython-35m-darwin.so: dlopen(/XXX/jpy/build/lib.macosx-10.6-intel-3.5/jpy.cpython-35m-darwin.so, 1): Symbol not found: _PyBool_Type
  Referenced from: /XXX/jpy/build/lib.macosx-10.6-intel-3.5/jpy.cpython-35m-darwin.so
  Expected in: flat namespace
 in /XXX/jpy/build/lib.macosx-10.6-intel-3.5/jpy.cpython-35m-darwin.so
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.jpy.PyLib.loadLib(PyLib.java:347)
	at org.jpy.PyLib.<clinit>(PyLib.java:396)
	at Test.main(Test.java:7)

Any help is appreciated

**Comment by mariobriggs** [comment]
I got past this (well atleast in a diff way)

I was using openJDK (for Java) and during build when running the python unit tests, 1 of them crashed and hence didnt go into the java tests. Then i tried my java sample and got the above error.

While trying to get the java tests to run as part of build, for some reason i switched to IBM Java JDK and the python unit test didnt crash and build then proceeded to the java unit tests. I did run into an error about PYTHONHOME... and following the very useful error message, set PYTHONHOME and the error went away.
