### ISSUE TITLE
java.lang.RuntimeException: missing configuration property 'jpy.jpyLib'

### ISSUE THREAD

**Issue by sandeep-gh** [bcdev/jpy#95]
Trying to give this a go but ran into this problem: 

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.jpy.PyModule.importModule(PyModule.java:91)
        at test_jpy.main(test_jpy.java:6)
Caused by: java.lang.RuntimeException: missing configuration property 'jpy.jpyLib'
        at org.jpy.PyLibConfig.getProperty(PyLibConfig.java:120)
        at org.jpy.PyLib.loadLib(PyLib.java:349)
        at org.jpy.PyLib.<clinit>(PyLib.java:405)
        ... 2 more

```

I am using java 1.8. The test code looks as follows:

```
import org.jpy.PyModule;
import org.jpy.PyObject;
public class test_jpy {

    public static void main(String[] args) {
        PyModule sys = PyModule.importModule("sys");
        PyObject path = sys.getAttribute("path");

    }

}

```

Thanks for taking a look.
-s

**Comment by sandeep-gh** [comment]
I got this working. Just to close the thread, below is the fully working code and instruction for compiling. 

```
import org.jpy.PyModule;
import org.jpy.PyObject;
import org.jpy.PyLib;

public class test_jpy {
    public static void main(String[] args) {
        PyLib.startPython();
        PyModule sys = PyModule.importModule("sys");
        PyObject path = sys.getAttribute("path");
        path.call("append", "/home/sandeep/NDSSL-Software/jpy_step_by_step");
        PyModule dumdum = PyModule.importModule("dummy");
        dumdum.call("heyho");
        PyLib.stopPython();
    }
}


```
javac -cp "/home/pgxxc/opensource_projects/source/jpy/lib/jpy-0.9-SNAPSHOT.jar" test_jpy.java

java -Djpy.jpyLib=/home/pgxxc/opensource_projects/source/jpy/build/lib.linux-x86_64-2.7/jpy.so -Djpy.jdlLib=/home/pgxxc/opensource_projects/source/jpy/build/lib.linux-x86_64-2.7/jdl.so  -cp "./:/home/pgxxc/opensource_projects/source/jpy/lib/jpy-0.9-SNAPSHOT.jar" test
```

**Comment by forman** [comment]
Note, you can also 

* use Java's library path `java -Djava.library.path=/home/pgxxc/opensource_projects/source/jpy/build/lib.linux-x86_64-2.7:$LD_LIBRARY_PATH` ...
* or use a properties file: `java -Djpy.config=path/to/jpyconfig.properties` ...

with `jpyconfig.properties` being:
```
    jpy.jpyLib = /home/pgxxc/opensource_projects/source/jpy/build/lib.linux-x86_64-2.7/jpy.so
    jpy.jdlLib = /home/pgxxc/opensource_projects/source/jpy/build/lib.linux-x86_64-2.7/jdl.so
    # If you still get java.lang.UnsatisfiedLinkError, also specify location of shared Python library:
    #jpy.pythonLib = /path/to/python.so
```
